name: docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Use the latest version of the action.

      - name: Set up Python 3.12
        uses: actions/setup-python@v2 # Use the latest version of the action.
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          pip install poetry
          poetry --version

      - name: Install Dependencies
        run: |
          # Activate the virtual environment if using Poetry
          source .venv/bin/activate

          # Install dependencies using Poetry
          poetry install --no-interaction

          # Install additional dependencies from a requirements file
          pip install -r docs/source/requirements.txt

      - name: Build Documentation
        run: |
          cd docs/
          bash ./build.sh

      - name: Push docs
        run: |
          git config --global user.name 'showierdata9978'
          git config --global user.email 'showierdata9978@users.noreply.github.com'
          git add docs/
          git commit -m "Update documentation"
          git push


      
