name: docs

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: umbuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install Dependencies
        run: |
          #assume im in the Venv
          C:\Users\runneradmin\.local\bin\poetry.exe install --no-interaction 
          $act
          pip install -r docs/source/requirements.txt
      - name: Build Documentation
        run: |
          cd docs/
          bash ./build.sh
      - name: Push docs
        run: |
          git config --global user.name 'showierdata9978'
          git config --global user.email 'showierdata9978@users.noreply.github.com'
          git commit -am "Update documentation"
          git push
   
      
          

      
